# Generated by Django 5.2.4 on 2025-07-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
